version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-2
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'santhosh-2'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'password'
    ports:
      - 5437:5432
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db: